"""Exports: Word (.docx), PDF (via LibreOffice), Markdown, TXT, SRT."""
from __future__ import annotations

import re
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional

from docx import Document
from docx.enum.section import WD_ORIENT  # noqa: F401
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

from .minutes import fmt_ts

ACCENT = RGBColor(0x0E, 0x5E, 0x78)   # deep cyan – prints well
GOLD = "C9A227"
HEAD_FILL = "0E5E78"
ZEBRA = "EEF5F7"

LABELS = {
    "en": {"minutes": "Minutes of Meeting", "date": "Date", "time": "Time", "duration": "Duration",
           "platform": "Platform", "attendees": "Attendees", "name": "Name", "role": "Role",
           "agenda": "Agenda", "discussion": "Discussion", "decisions": "Decisions",
           "actions": "Action Items", "task": "Action", "owner": "Owner", "due": "Due",
           "issues": "Open Issues & Risks", "next": "Next Meeting", "tldr": "TL;DR",
           "exec": "Executive Summary", "summary": "Summary", "transcript": "Appendix — Full Transcript",
           "page": "Page", "of": "of", "none": "None recorded.", "generated": "Generated by MinuteTaker"},
    "el": {"minutes": "Πρακτικά Συνάντησης", "date": "Ημερομηνία", "time": "Ώρα", "duration": "Διάρκεια",
           "platform": "Πλατφόρμα", "attendees": "Συμμετέχοντες", "name": "Όνομα", "role": "Ρόλος",
           "agenda": "Ατζέντα", "discussion": "Συζήτηση", "decisions": "Αποφάσεις",
           "actions": "Ενέργειες", "task": "Ενέργεια", "owner": "Υπεύθυνος", "due": "Προθεσμία",
           "issues": "Ανοιχτά Θέματα & Κίνδυνοι", "next": "Επόμενη Συνάντηση", "tldr": "Με μια ματιά",
           "exec": "Συνοπτική Περίληψη", "summary": "Περίληψη", "transcript": "Παράρτημα — Πλήρης Απομαγνητοφώνηση",
           "page": "Σελίδα", "of": "από", "none": "Δεν καταγράφηκε.", "generated": "Δημιουργήθηκε με το MinuteTaker"},
}


def labels(lang: Optional[str]) -> dict:
    return LABELS.get(lang or "en", LABELS["en"])


def fmt_duration(sec: float) -> str:
    sec = int(sec or 0)
    h, m = sec // 3600, sec % 3600 // 60
    if sec < 60:
        return f"{sec} s"
    return f"{h}h {m:02d}m" if h else f"{m} min"


def _dt(meeting: dict) -> tuple[str, str]:
    raw = meeting.get("started_at") or ""
    try:
        d = datetime.fromisoformat(raw.replace("Z", "+00:00")).astimezone()
        return d.strftime("%d/%m/%Y"), d.strftime("%H:%M")
    except Exception:
        return raw[:10], ""


def safe_filename(name: str) -> str:
    name = re.sub(r"[^\w\-. ]+", "", name, flags=re.U).strip() or "meeting"
    return name[:80]


# --------------------------------------------------------------------- docx --
def _shade(cell, hex_fill: str) -> None:
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    tcPr.append(shd)


def _field(run, instr: str) -> None:
    for tag, text in (("begin", None), (None, instr), ("end", None)):
        if tag:
            el = OxmlElement("w:fldChar")
            el.set(qn("w:fldCharType"), tag)
        else:
            el = OxmlElement("w:instrText")
            el.set(qn("xml:space"), "preserve")
            el.text = text
        run._r.append(el)


def _bottom_border(paragraph, color: str = GOLD, size: int = 12) -> None:
    pPr = paragraph._p.get_or_add_pPr()
    bdr = OxmlElement("w:pBdr")
    b = OxmlElement("w:bottom")
    for k, v in (("w:val", "single"), ("w:sz", str(size)), ("w:space", "4"), ("w:color", color)):
        b.set(qn(k), v)
    bdr.append(b)
    pPr.append(bdr)


def _table(doc, headers: list[str], rows: list[list[str]], widths: list[float]):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, h in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = ""
        r = c.paragraphs[0].add_run(h)
        r.bold, r.font.color.rgb, r.font.size = True, RGBColor(0xFF, 0xFF, 0xFF), Pt(10)
        _shade(c, HEAD_FILL)
    for n, row in enumerate(rows):
        cells = t.add_row().cells
        for i, v in enumerate(row):
            cells[i].text = ""
            cells[i].paragraphs[0].add_run(str(v)).font.size = Pt(10)
            if n % 2:
                _shade(cells[i], ZEBRA)
    t.autofit = False
    grid = t._tbl.tblGrid
    for i, w in enumerate(widths):
        t.columns[i].width = Cm(w)
        gc = grid.findall(qn("w:gridCol"))
        if i < len(gc):
            gc[i].set(qn("w:w"), str(int(Cm(w).twips)))
    for row in t.rows:
        for i, w in enumerate(widths):
            row.cells[i].width = Cm(w)
    # repeat header row on each page
    trPr = t.rows[0]._tr.get_or_add_trPr()
    h = OxmlElement("w:tblHeader")
    h.set(qn("w:val"), "true")
    trPr.append(h)
    doc.add_paragraph()
    return t


def _h(doc, text: str, level: int = 1):
    p = doc.add_heading(text, level=level)
    for r in p.runs:
        r.font.color.rgb = ACCENT
    return p


def _bullets(doc, items: list[str], none: str) -> None:
    if not items:
        doc.add_paragraph(none).runs[0].italic = True
        return
    for it in items:
        doc.add_paragraph(it, style="List Bullet")


def to_docx(path: Path, meeting: dict, minutes: Optional[dict], summaries: dict, segments: list[dict],
            *, include_transcript: bool = True, include_summary: bool = True, include_timestamps: bool = True,
            company: str = "", logo: Optional[str] = None) -> Path:
    m = minutes or {}
    L = labels(m.get("language") or meeting.get("language"))
    doc = Document()

    st = doc.styles["Normal"]
    st.font.name, st.font.size = "Calibri", Pt(11)
    st.element.rPr.rFonts.set(qn("w:eastAsia"), "Calibri")
    for s in ("Heading 1", "Heading 2", "Title"):
        doc.styles[s].font.name = "Calibri"

    sec = doc.sections[0]
    sec.page_height, sec.page_width = Cm(29.7), Cm(21.0)   # A4
    for side in ("left_margin", "right_margin"):
        setattr(sec, side, Cm(2.2))
    sec.top_margin, sec.bottom_margin = Cm(2.0), Cm(2.0)

    # header: company / logo
    hp = sec.header.paragraphs[0]
    if logo and Path(logo).exists():
        hp.add_run().add_picture(logo, height=Cm(1.0))
        hp.add_run("   ")
    if company:
        r = hp.add_run(company)
        r.font.size, r.font.color.rgb = Pt(9), RGBColor(0x66, 0x66, 0x66)
    # footer: page X of Y
    fp = sec.footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for txt, fld in ((f"{L['page']} ", "PAGE"), (f" {L['of']} ", "NUMPAGES")):
        r = fp.add_run(txt)
        r.font.size = Pt(9)
        fr = fp.add_run()
        fr.font.size = Pt(9)
        _field(fr, fld)

    # title block
    kicker = doc.add_paragraph()
    kr = kicker.add_run(L["minutes"].upper())
    kr.bold, kr.font.size, kr.font.color.rgb = True, Pt(10), RGBColor(0xC9, 0xA2, 0x27)
    title = doc.add_paragraph()
    tr = title.add_run(m.get("title") or meeting.get("title") or "")
    tr.bold, tr.font.size, tr.font.color.rgb = True, Pt(22), ACCENT
    _bottom_border(title)

    date, time = _dt(meeting)
    meta = doc.add_table(rows=1, cols=4)
    for i, (k, v) in enumerate(((L["date"], date), (L["time"], time),
                                (L["duration"], fmt_duration(meeting.get("duration_s"))),
                                (L["platform"], meeting.get("platform") or ""))):
        c = meta.rows[0].cells[i]
        c.text = ""
        p = c.paragraphs[0]
        kr = p.add_run(k.upper() + "\n")
        kr.font.size, kr.font.color.rgb, kr.bold = Pt(8), RGBColor(0x77, 0x77, 0x77), True
        vr = p.add_run(v)
        vr.font.size, vr.bold = Pt(11), True
        _shade(c, ZEBRA)
    doc.add_paragraph()

    if include_summary and (m.get("tldr") or m.get("executive_summary") or summaries):
        _h(doc, L["summary"])
        tldr = m.get("tldr") or [x for x in (summaries.get("tldr") or "").split("\n") if x.strip()]
        if tldr:
            doc.add_paragraph().add_run(L["tldr"]).bold = True
            _bullets(doc, [t.lstrip("•- ").strip() for t in tldr], L["none"])
        es = m.get("executive_summary") or summaries.get("executive") or ""
        if es:
            doc.add_paragraph().add_run(L["exec"]).bold = True
            for para in es.split("\n\n"):
                doc.add_paragraph(para.strip())

    if minutes:
        _h(doc, L["attendees"])
        att = m.get("attendees") or []
        if att:
            _table(doc, ["#", L["name"], L["role"]],
                   [[str(i + 1), a["name"], a.get("role", "")] for i, a in enumerate(att)], [1.2, 8, 7.4])
        else:
            doc.add_paragraph(L["none"]).runs[0].italic = True

        if m.get("agenda"):
            _h(doc, L["agenda"])
            for a in m["agenda"]:
                doc.add_paragraph(a, style="List Number")

        _h(doc, L["discussion"])
        if not m.get("discussion"):
            doc.add_paragraph(L["none"]).runs[0].italic = True
        for i, d in enumerate(m.get("discussion") or []):
            _h(doc, f"{i + 1}. {d['topic']}", 2)
            _bullets(doc, d.get("points") or [], L["none"])

        _h(doc, L["decisions"])
        if m.get("decisions"):
            _table(doc, ["#", L["decisions"]], [[f"D{i + 1}", d] for i, d in enumerate(m["decisions"])], [1.4, 15.2])
        else:
            doc.add_paragraph(L["none"]).runs[0].italic = True

        _h(doc, L["actions"])
        if m.get("action_items"):
            _table(doc, ["#", L["task"], L["owner"], L["due"]],
                   [[f"A{i + 1}", a["task"], a.get("owner", ""), a.get("due", "")]
                    for i, a in enumerate(m["action_items"])], [1.2, 9.4, 3.4, 2.6])
        else:
            doc.add_paragraph(L["none"]).runs[0].italic = True

        _h(doc, L["issues"])
        _bullets(doc, m.get("open_issues") or [], L["none"])

        if m.get("next_meeting"):
            _h(doc, L["next"])
            doc.add_paragraph(m["next_meeting"])

    if include_transcript and segments:
        doc.add_page_break()
        _h(doc, L["transcript"])
        for s in segments:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(3)
            if include_timestamps:
                tr = p.add_run(f"[{fmt_ts(s['start_s'])}] ")
                tr.font.size, tr.font.color.rgb = Pt(8.5), RGBColor(0x88, 0x88, 0x88)
            sr = p.add_run(f"{s.get('speaker') or '?'}: ")
            sr.bold, sr.font.size, sr.font.color.rgb = True, Pt(9.5), ACCENT
            p.add_run(s["text"]).font.size = Pt(9.5)

    end = doc.add_paragraph()
    er = end.add_run(L["generated"])
    er.font.size, er.font.color.rgb = Pt(8), RGBColor(0x99, 0x99, 0x99)
    end.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    doc.save(str(path))
    return path


# ------------------------------------------------------------------ others --
def to_markdown(meeting: dict, minutes: Optional[dict], summaries: dict, segments: list[dict],
                include_transcript: bool = True, include_summary: bool = True) -> str:
    m = minutes or {}
    L = labels(m.get("language") or meeting.get("language"))
    date, time = _dt(meeting)
    out = [f"# {m.get('title') or meeting.get('title')}", "",
           f"**{L['date']}:** {date} {time} · **{L['duration']}:** {fmt_duration(meeting.get('duration_s'))} · "
           f"**{L['platform']}:** {meeting.get('platform')}", ""]
    if include_summary:
        if m.get("tldr"):
            out += [f"## {L['tldr']}", *[f"- {t}" for t in m["tldr"]], ""]
        if m.get("executive_summary"):
            out += [f"## {L['exec']}", m["executive_summary"], ""]
    if minutes:
        out += [f"## {L['attendees']}", *[f"- {a['name']}" + (f" — {a['role']}" if a.get("role") else "")
                                          for a in m.get("attendees", [])], ""]
        if m.get("agenda"):
            out += [f"## {L['agenda']}", *[f"{i + 1}. {a}" for i, a in enumerate(m["agenda"])], ""]
        out += [f"## {L['discussion']}"]
        for d in m.get("discussion", []):
            out += [f"### {d['topic']}", *[f"- {p}" for p in d.get("points", [])], ""]
        out += [f"## {L['decisions']}", *[f"- **D{i + 1}** {d}" for i, d in enumerate(m.get("decisions", []))], ""]
        out += [f"## {L['actions']}", f"| # | {L['task']} | {L['owner']} | {L['due']} |", "|---|---|---|---|",
                *[f"| A{i + 1} | {a['task']} | {a.get('owner', '')} | {a.get('due', '')} |"
                  for i, a in enumerate(m.get("action_items", []))], ""]
        out += [f"## {L['issues']}", *[f"- {x}" for x in m.get("open_issues", [])], ""]
        if m.get("next_meeting"):
            out += [f"## {L['next']}", m["next_meeting"], ""]
    if include_transcript and segments:
        out += [f"## {L['transcript']}", *[f"`[{fmt_ts(s['start_s'])}]` **{s.get('speaker')}:** {s['text']}"
                                          for s in segments]]
    return "\n".join(out) + "\n"


def to_txt(segments: list[dict]) -> str:
    return "\n".join(f"[{fmt_ts(s['start_s'])}] {s.get('speaker')}: {s['text']}" for s in segments) + "\n"


def _srt_ts(t: float) -> str:
    ms = int(round(t * 1000))
    return f"{ms // 3600000:02d}:{ms % 3600000 // 60000:02d}:{ms % 60000 // 1000:02d},{ms % 1000:03d}"


def to_srt(segments: list[dict]) -> str:
    return "\n".join(f"{i + 1}\n{_srt_ts(s['start_s'])} --> {_srt_ts(s['end_s'])}\n{s.get('speaker')}: {s['text']}\n"
                     for i, s in enumerate(segments))


def soffice() -> Optional[str]:
    for name in ("soffice", "libreoffice"):
        p = shutil.which(name)
        if p:
            return p
    for p in (r"C:\Program Files\LibreOffice\program\soffice.exe",
              "/Applications/LibreOffice.app/Contents/MacOS/soffice"):
        if Path(p).exists():
            return p
    return None


def docx_to_pdf(docx_path: Path) -> Path:
    exe = soffice()
    if not exe:
        raise RuntimeError("PDF export needs LibreOffice installed (or open the .docx in Word and Save as PDF)")
    subprocess.run([exe, "--headless", "--convert-to", "pdf", "--outdir", str(docx_path.parent), str(docx_path)],
                   check=True, capture_output=True, timeout=180)
    pdf = docx_path.with_suffix(".pdf")
    if not pdf.exists():
        raise RuntimeError("PDF conversion failed")
    return pdf
